name: Iheanyi Ekechukwu
description: Iheanyi Ekechukwu is a Senior studying Computer Science and Graphic Design at the University of Notre Dame.
safe: true

markdown: redcarpet
pygments: true
permalink: pretty